
version: 0.2

env:
  variables:
    REAL_BUILD_DIR: /go/src/github.com/jerryz920


phases:
  pre_build:
    commands:
      - echo "fixing the go directory structure to search for deps"
      - echo "current src directory is $CODEBUILD_SRC_DIR"
      - mkdir -p $REAL_BUILD_DIR
      - ln -s $CODEBUILD_SRC_DIR $REAL_BUILD_DIR/sample-app
  build:
    commands:
      - echo "building $REAL_BUILD_DIR"
      - cd $REAL_BUILD_DIR/sample-app
      - go build

artifacts:
  files:
    - sample-app
    - appspec.yml
    - index.html
    - scripts/*
