
version: 0.2

phases:
  pre_build:
    commands:
      - echo "prebuild-pwd " `pwd`
      - echo "GOPATH=$GOPATH, GOROOT=$GOROOT"
      - ls
      - which go
  build:
    commands:
      - echo "pwd = " `pwd` 
      - echo "GOPATH=$GOPATH, GOROOT=$GOROOT"
      - go version
      - go build

artifacts:
  files:
    - sample-app
