
version: 0.2

phases:
  install:
    commands:
      - go get -u github.com/kardianos/govendor
  pre_build:
      - echo "prebuild-pwd " `pwd`
      - govendor install
  build:
    commands:
      - echo "pwd = " `pwd` 
      - echo "GOPATH=$GOPATH, GOROOT=$GOROOT"
      - go version
      - go build

artifacts:
  files:
    - sample-app
